Chinese translations
welpo/tabi pull request #166
Opened 2023-09-18 09:21 UTC by Smtbook

I added Traditional and Simplfied Chinese translations to the theme, but I am unsure about the language codes for them.

2023-09-18 10:09 UTC, welpo commented
Thank you so much, @Smtbook!

Let me think about the language codes and get back to you. Maybe we can use BCP 47.

2023-09-18 11:37 UTC, welpo requested changes
The `about_feeds` must contain "About Feeds" (in plural) so it becomes a link.

Regarding the filenames, I think it makes most sense to use [BCP-47 codes](https://en.wikipedia.org/wiki/IETF_language_tag).

So Simplified Chinese would be `zh-Hans`, and Traditional Chinese `zh-Hant`.

Thanks again!

2023-09-18 11:37 UTC, welpo commented on i18n/zh-CN.toml
> +about_feeds = "这是Web Feed，又称为Atom Feed，把现在的网址复制到新闻阅读器即可订阅本站文章。造访「About Feed」来了解更多资讯。"
should contain "About Feeds" (missing the s in "Feeds") so it becomes a link in the [Stylized feed](https://welpo.github.io/tabi/atom.xml)

2023-09-18 11:37 UTC, welpo commented on i18n/zh-TW.toml
> +about_feeds = "這是Web Feed，又稱為Atom Feed，把現在的網址複製到新聞閱讀器即可訂閱本站文章。造訪「About Feed」來了解更多資訊。"
should contain "About Feeds" (missing the s in "Feeds") so it becomes a link in the [Stylized feed](https://welpo.github.io/tabi/atom.xml)

2023-09-19 07:54 UTC, Smtbook commented
The issues has been corrected now.

2023-09-19 07:55 UTC, Smtbook commented
The issues has been corrected.

2023-09-19 11:28 UTC, welpo approved these changes

2023-09-19 11:31 UTC, merged

2023-09-19 11:31 UTC, welpo commented
多谢!